### ISSUE TITLE
Starting time can be wrong (should be expressed in midi ticks)

### ISSUE THREAD

**Issue by tuomaseerola** [miditoolbox/1.1#3]
https://github.com/miditoolbox/1.1/blob/d339c4ade07ead6e746f2cc51708eb6360781f30/miditoolbox/mdlMStrToNMat.m#L53

**Comment by tuomaseerola** [comment]
A fix proposed by Luigi Marino 26 August 2020:
`  cumtime=midi.ticks_per_quarter_note; % fix suggested by Luigi Marino 26 August 2020
`

**Comment by miditoolbox** [comment]
Fixed
